### ISSUE TITLE
Builds but doesn't work.

### ISSUE THREAD

**Issue by castlevania11** [ModTheGungeon/ETGMod.Reloaded#1]
I get a black screen when I try to run Gungeon with the DLLs made from MonoMod. No crashes.

**Comment by zatherz** [comment]
Are you using MonoMod directly? If so, you shouldn't. You should use https://github.com/modthegungeon/Installer.Headless, and add a custom local component (tell me if you need help with that).

**Comment by castlevania11** [comment]
How do I do that?

**Comment by zatherz** [comment]
Run `mtginstaller components` to create the basic config files. After that, you'll have a `Mod the Gungeon` folder in %appdata%. Open the `custom-components.yml` file inside, delete all content in it, and then paste this (filling in the proper fields):
```yaml
- name: ETGMod_local
  versions:
    - key: latest
      name: Latest local build
      path: 'C:\PATH\TO\ETGMOD.zip'
      requires_patched_exe: true
```
After that, you should be able to run `mtginstaller install ETGMod_local` to install your local ETGMod build.

By the way, a while ago I released the first beta of the installer and of ETGMod Reloaded. You can download the installer from https://modthegungeon.zatherz.eu, and install Reloaded by running `mtginstaller install ETGMod`.
